-module(p2).

-export([answer/0]).

%% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
%% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%% Find the sum of all the even-valued terms in the sequence which do not exceed four million.

answer() ->
    even_fib(0, 1, 0).

even_fib(X, Y, Sum) when Y < 4000000 ->
    Z = X+Y,
    NewSum = case Z rem 2 =:= 0 of
                  true -> Sum + Z;
                  _Else -> Sum
              end,
    even_fib(Y, Z, NewSum);
even_fib(_X, _Y, Sum) -> Sum.
